### PR TITLE
ci: switch to github workflow

### PR DESCRIPTION
**Pull request by psafont**
The whole deployment to github pages is untested.

The doc generator generator should work by creating 4 files in .gh-pages:
```
datapath.html.md
plugin.html.md
task.html.md
volume.html.md
```
Then wipe the directory source/includes in the branch slate: https://github.com/xapi-project/xapi-storage/tree/slate/source/includes (hence the keep_files: false, publish_branch: slate and destination_dir: source/includes )

and commiting the newly created files in that branch and directory.

If it goes wrong, I'll just have to manually intervene

The tests are happy: https://github.com/psafont/xapi-storage/runs/6778115598?check_suite_focus=true

### CODE REVIEW

**Review by MarkSymsCtx — APPROVED** [review]
It looks reasonably sensible but only trying it will tell for sure

**Comment by undu** [comment]
xapi-storage is a part of xen-api now, a different approach for generating docs should be taken: https://github.com/xapi-project/xen-api/commits/master/ocaml/xapi-storage

**Comment by MarkSymsCtx** [comment]
> xapi-storage is a part of xen-api now, a different approach for generating docs should be taken: https://github.com/xapi-project/xen-api/commits/master/ocaml/xapi-storage

This repository should be retired then otherwise it will cause confusion

**Comment by psafont** [comment]
Cleanup actions need to be decided, these repositories might still be required for LCM fixes. Replacing the content of the master branch to point out the current situation is the option I'm leaning towards the most. This should allow to keep publishing docs from the other repository while having the LCM branch available if needed

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
Work is done in https://github.com/xapi-project/xen-api/pull/4729

**Pull request closed without merging**
