### PR TITLE
CP-27826: Automatically update Slate docs from generated markdown files

### PR DESCRIPTION
**Pull request by gaborigloi**
And remove the old HTML docs. The new docs are in the `slate` branch, we push there the new generated markdown files. The Travis build of that branch updates the `gh-pages` branch containing the actual website.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
It's already online: https://xapi-project.github.io/xapi-storage :)

**Comment by mseri** [comment]
`+14 −35,497`

**Comment by olivierlambert** [comment]
Thanks for the doc guys! Is there a way to add a very simple example? I don't know, NFS or local ext?

**Comment by gaborigloi** [comment]
I don't know of any up to date one, and the SMAPIv3 interface has not been finalized yet, but there is an outdated example here: https://github.com/xapi-project/ffs

**Comment by olivierlambert** [comment]
okay, I'll take a look. When you'll finalize the smapiv3 interface, please make a simple example, I'm eager to write "plugins"!

**Pull request merged**
