### PR TITLE
Replaced jbuild files with dune.

### PR DESCRIPTION
**Pull request by kc284**
Please note that `make test` fails, but this is not caused by this PR (needs to be updated to use the latest interface from rpclib).

### CODE REVIEW

**Comment by lindig** [comment]
I see this in the Travis build. The build succeeds and this is the part of the test that fails:
```
 File "generator/test/storage_test.ml", line 70, characters 17-28:
- Error: Unbound module type Idl.RPCfunc
[ERROR] The compilation of xapi-storage failed at "/home/opam/.opam/4.07/bin/dune runtest -p xapi-storage -j 127".
```

**Comment by kc284** [comment]
Indeed; this module type and others were removed from the rpclib, but neither the README in rpclib was updated not the tests here.

**Comment by lindig** [comment]
I don't understand why this has not lead to failures of xs-opam on Travis and I would expect failures if we merge. I think the tests should be disabled in the opam file for now to avoid this.

**Comment by kc284** [comment]
The job in xs-opam installs packages but does not seem to run tests. It might be a good idea to run them so as to catch cases like this.

**Pull request merged**
